import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="bg-gray-50 text-gray-800 font-sans min-h-screen flex flex-col">
      <Head>
        <title>Terms of Service & Disclaimer | Rentcalo</title>
        <meta name="description" content="Read the Terms of Service and legal disclaimers for Rentcalo. Our short-term rental calculators are for educational purposes and do not constitute financial advice." />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
        <link rel="canonical" href="https://www.rentcalo.com/terms-of-service" />
      </Head>

      <main className="flex-grow container mx-auto px-4 py-12 max-w-5xl">
        <div className="bg-white p-8 md:p-12 rounded-3xl shadow-sm border border-gray-100">
          <h1 className="text-4xl font-extrabold text-gray-900 mb-4 border-b pb-4">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-8"><strong>Last Updated:</strong> May 2026</p>
          
          <div className="space-y-8 text-lg text-gray-700 leading-relaxed">
            
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
              <p>By accessing and using <strong>Rentcalo</strong> (www.rentcalo.com), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use our website or calculators.</p>
            </div>

            {/* CRITICAL FOR YMYL / ADSENSE: Financial Disclaimer */}
            <div className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-xl font-bold text-gray-900 mb-3">2. Educational Purposes Only (Not Financial Advice)</h2>
              <p className="text-sm md:text-base">
                All content, calculators, and tools provided on Rentcalo are intended for <strong>educational and informational purposes only</strong>. The calculations generated by our platform regarding ROI, cap rates, cash flow, and net payouts are estimates based on user-provided inputs and publicly available platform fee structures. 
              </p>
              <p className="text-sm md:text-base mt-2">
                <strong>We do not provide legal, tax, or financial advice.</strong> You should always conduct your own due diligence and consult with a licensed CPA or financial advisor before making any real estate investments or signing arbitrage master leases.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">3. Trademarks and Brand Affiliation</h2>
              <p>Rentcalo is an independent, third-party analytics tool created to assist short-term rental hosts and real estate investors. We are <strong>NOT</strong> affiliated, associated, authorized, endorsed by, or in any way officially connected with Airbnb, Inc., Booking.com, Vrbo, Agoda, Expedia Group, or any of their subsidiaries. All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">4. Accuracy of Information</h2>
              <p>While we strive to keep our algorithms updated with the latest platform fee structures (such as Airbnb's 15.5% simplified pricing model or VRBO's processing fees), platforms change their terms frequently. We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or availability of the calculations. You should always verify final payout amounts directly within your host dashboards.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">5. Limitation of Liability</h2>
              <p>In no event shall Rentcalo, its creators, or its team be liable for any direct, indirect, incidental, consequential, or special damages (including but not limited to loss of data, loss of profits, or business interruption) arising out of or in any way connected with your use of our calculators or reliance on the information provided on this website.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">6. Links to Third-Party Websites</h2>
              <p>Our website may contain links to third-party websites or services that are not owned or controlled by Rentcalo. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites. For more information on how we handle third-party cookies and data, please review our <Link href="/privacy-policy" className="text-blue-600 font-bold hover:underline">Privacy Policy</Link>.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">7. Contact Information</h2>
              <p>If you have any questions or concerns regarding these Terms of Service, or if you spot a change in platform fees that needs updating in our calculators, please reach out to us at <a href="mailto:support@rentcalo.com" className="text-blue-600 font-bold hover:underline">support@rentcalo.com</a>.</p>
            </div>

          </div>
        </div>
      </main>
    </div>
  );
}